name: BlazorEngine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 10.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
    - name: Restore dependencies
      run: dotnet restore src/BlazorEngine/BlazorEngine.csproj
    - name: Build
      run: dotnet build --no-restore src/BlazorEngine/BlazorEngine.csproj
    - name: Pack    
      if: github.event_name != 'pull_request'
      run: dotnet pack "src/BlazorEngine/BlazorEngine.csproj" -c Release -o out -p:PackageVersion=1.0.${{ github.run_number }}
    - name: Push generated package to GitHub registry
      if: github.event_name != 'pull_request'
      run: dotnet nuget push ./out/*.nupkg --source "https://nuget.pkg.github.com/f4n0/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} 
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  

    - name: Push generated package to Nuget registry
      if: github.event_name != 'pull_request'
      env:
        NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}  
      run: dotnet nuget push ./out/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key "$NUGET_TOKEN"
      